apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: spaceships.thomasvn.dev
spec:
  group: thomasvn.dev
  names:
    kind: Spaceship
    listKind: SpaceshipList
    plural: spaceships
    singular: spaceship
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Spaceship is a custom resource exemplar
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: SpaceshipSpec is the spec for a Spaceship resource
            type: object
            properties:
              name:
                type: string
              model:
                type: string
              fuel:
                type: integer
          status:
            description: SpaceshipStatus is the status for a Spaceship resource
            type: object
            properties:
              publishedAt:
                type: string
    served: true
    storage: true
    subresources:
      status: {}
