apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # Name must match the spec fields below, and be in the form: <plural>.<group>
  name: spaceships.thomasvn.dev
spec:
  # Group name to use for REST API: /apis/<group>/<version>
  group: thomasvn.dev
  names:
    kind: Spaceship
    listKind: SpaceshipList
    plural: spaceships
    singular: spaceship
  scope: Namespaced
  # List of versions supported by this CustomResourceDefinition
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    schema:
      openAPIV3Schema:
        description: Spaceship is a custom resource exemplar
        type: object
        properties:
          spec:
            description: SpaceshipSpec is the spec for a Spaceship resource
            type: object
            properties:
              name:
                type: string
              model:
                type: string
              launchdate:
                type: string
              duration:
                type: integer
